version: 2
jobs:
  build:
    context: docker-hub
    machine: true
    steps:
      - checkout

      - run: docker build -t jimrazmus/awscli .

      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push jimrazmus/awscli:latest